"""add title changed by user to conversations

Revision ID: 050291b7b35a
Revises: 9ffd74fb24cd
Create Date: 2026-07-24 19:44:53.853413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050291b7b35a'
down_revision: Union[str, Sequence[str], None] = '9ffd74fb24cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'conversations',
        sa.Column(
            'title_changed_by_user',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'title_changed_by_user')
    # ### end Alembic commands ###
