"""add tool state lifecycle

Revision ID: 83245765c129
Revises: cfc095da9d42
Create Date: 2026-07-16 14:06:58.948110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83245765c129'
down_revision: Union[str, Sequence[str], None] = 'cfc095da9d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DELETE FROM conversation_tool_state")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_tool_state', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('conversation_tool_state', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint('uq_conversation_tool_state_user_conversation', 'conversation_tool_state', ['user_id', 'conversation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_conversation_tool_state_user_conversation', 'conversation_tool_state', type_='unique')
    op.drop_column('conversation_tool_state', 'expires_at')
    op.drop_column('conversation_tool_state', 'created_at')
    # ### end Alembic commands ###
