TOOL_DESCRIPTIONS = {
    "get_current_time": "Return the current date or time.",
    "get_tools_info": "List every backend tool currently available to Jarvis.",
    "get_unread_emails": "List or search unread received Gmail messages without reading full bodies.",
    "get_latest_emails": "List the newest received Gmail messages without reading full bodies.",
    "gmail_search_email_message": "Search received Gmail messages by sender, keywords, or dates.",
    "gmail_get_drafted_emails": "List the newest Gmail drafts.",
    "gmail_create_email_draft": "Create one new Gmail draft without sending it.",
    "gmail_search_drafted_emails": "Search Gmail drafts by recipient, keywords, or dates.",
    "gmail_read_specific_draft": "Read one exact Gmail draft, including its complete body.",
    "gmail_update_email_draft": "Update one exact Gmail draft without sending it.",
    "gmail_send_drafted_email": "Send one exact existing Gmail draft.",
    "gmail_create_multiple_email_drafts": "Create several Gmail drafts without sending them.",
    "gmail_read_latest_email": "Read the complete latest or penultimate received Gmail message.",
    "gmail_read_specific_email": "Search and read one exact received Gmail message.",
    "gmail_move_email_to_trash": "Move one exact received Gmail message to Trash.",
    "gmail_move_sent_email_to_trash": "Move one exact sent Gmail message to Trash.",
    "gmail_delete_draft": "Permanently delete one exact Gmail draft.",
    "gmail_create_reply_draft": "Create a reply draft for one exact received Gmail message.",
    "gmail_get_sent_emails": "List the newest sent Gmail messages without reading full bodies.",
    "gmail_search_sent_emails": "Search sent Gmail messages by recipient, keywords, or dates.",
    "calendar_create_event": "Prepare an event or create the exact pending event after explicit confirmation.",
    "calendar_get_upcoming_events": "Read events in a date range without modifying Calendar.",
    "calendar_find_free_slots": "Read busy periods and calculate free windows for a requested duration.",
    "calendar_update_event": "Select and prepare an event update, or apply the pending update after confirmation.",
    "calendar_delete_event": "Select an event for deletion, or delete the exact pending event after confirmation.",
    "calendar_prepare_event_from_email": "Select an exact Gmail item and extract a non-mutating event proposal.",
}
